server:
  port: 80

spring:
  application:
    name: consul-consumer

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register: false
        service-name: ${spring.application.name}
